server:
  port: 8002
  servlet:
    context-path: "/business"
    application-display-name: businessService
spring:
  application:
    name: businessService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    username: business
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/**/*.xml